[package]
name = "komopaper"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
komorebi-client = { git = "https://github.com/LGUG2Z/komorebi" }
serde_json = "1.0.140"
windows = "0.61.1"
anyhow = "1.0.98"
